### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by LizzyFleckenstein03** [anon55555/mt#1]
When trying to run this I get these errors:
```
# github.com/anon55555/mt/rudp
src/github.com/anon55555/mt/rudp/process.go:111:28: c.ackchans.LoadAndDelete undefined (type sync.Map has no field or method LoadAndDelete)
src/github.com/anon55555/mt/rudp/send.go:159:8: p.ping.Reset undefined (type *time.Ticker has no field or method Reset)
```
I know that this is probably because I did something wrong but its hard to do it correctly if there are no instructions :)

**Comment by anon55555** [comment]
You have an old version of Go.

**Comment by anon55555** [comment]
I'll add a go.mod file so it will say `note: module requires Go 1.15` if it fails to compile on an old version.

**Comment by LizzyFleckenstein03** [comment]
> You have an old version of Go.

Ok lol, I had just installed it. Guess I'll need to build it from source myself, the apt repo is pretty legacy.

**Comment by anon55555** [comment]
You can get binaries from golang.org.

**Comment by Kimapr** [comment]
the issue is still not solved...
